### ISSUE TITLE
Missing required fields in organization error

### ISSUE THREAD

**Issue by suzybates** [singer-io/tap-pipedrive#20] opened 2018-04-26 13:58 UTC
I started seeing this error a few days ago

```
 Error persisting data for table "organizations": Record 0 did not conform to schema:
 #: 2 schema violations found
 #: required key [timeline_last_activity_time] not found
 #: required key [timeline_last_activity_time_by_owner] not found
```

I don't believe I have these fields in my pipedrive api, so I am wondering why they have been made required?

**Comment by dmosorast** [comment] 2018-04-26 14:26
Hi @suzybates, looks like this issue is a duplicate of #19. Closing it for now to keep the conversation in a single thread.

**Closed by dmosorast** 2018-04-26 14:26 UTC
