### ISSUE TITLE
Massive jump in data imported from October 8th, 2018

### ISSUE THREAD

**Issue by honkycat** [singer-io/tap-pipedrive#37] opened 2018-10-10 16:14 UTC
My daily imported rows in Stitch data went from a few hundred thousand to two million per-day overnight.

The offending table is the `dealflow` table.

**Comment by alewis-ce** [comment] 2018-10-11 21:12
I have a couple of ideas for reducing row count.
1. The stream was designed to grab the stage change information for all deals. It currently grabs anything that is a 'dealChange' object, but that could be limited to 'dealChange' objects with field keys equal to 'stage_id' so that it's not pulling other types of changes. The new` process_row` function inside `dealflow.py` would be:
```
def process_row(self, row):
    if row['object'] == 'dealChange' and row['data']['field_key'] == 'stage_id':
        return row['data']
```
This would reduce the number of rows, but would not offer any bookmarking.

2. As @dmosorast suggested, it should only grab deal ids where a stage change has been found in the appropriate time frame. I think you would look at the `stage_change_time` of the `deals` endpoint and only grab the deal id if that time is more recent than the last time Stitch synced the data. Something like:
```
this_page_ids = [response.json()['data'][i]['id'] for i in range(ndeals) 
 if response.json()['data'][i]['stage_change_time'] is not None 
 if pendulum.parse(response.json()['data'][i]['stage_change_time']) >= {some_time_variable}]
``` 

The question is then: what is `some_time_variable` ? It should be a variable that does not change as the stream iterates through each deal id, but remains constant and gets updated only when the stream starts or finishes syncing. I could imagine setting a variable at the top of `get_deal_ids` in the `PipedriveIterStream` class that would store the initial state (e.g., `checkpoint = self.initial_state`). `checkpoint` would remain the same as the stream iterated through all deal ids, while `self.earliest_state` would update in the same way that other streams update it, based on whatever `state_field` was set to in dealflow.py  &mdash; probably `log_time` from the `deals/{deal_id}/flow` endoint because the state update command happens after the pagination of each deal id at that endpoint, rather than at the `deals` endpoint. This would mean that the next time the stream ran, it's initial state would be equal to the most recent stage change `log_time` for _any_ deal id from the previous run. If the row count is dramatically reduced and the stream runs quickly, this should be fine. If updates to any deal id happen while the stream is running, those would be missed. 

@dmosorast @nick-mccoy @honkycat Thoughts?

**Comment by dmosorast** [comment] 2018-10-11 21:47
@alewis-ce Thank you for hopping in, that is exactly the kind of insight I was hoping you'd be able to provide! Child streams are always difficult to deal with, so your domain knowledge is very much appreciated. Overall, the plan you've outlined sounds good to me.

I can't speak to the first point, as I'm not very familiar with the semantics of Pipedrive's data. However, for your statement about updates that happen while the stream is running, one possible way to deal with this is to introduce an upper bound on your datetime comparison that is set to the time that the stream began running. It makes the boolean a bit more complex, but I believe it should solve for that problem, since you would not be grabbing any deals that were updated after the stream began.

So, if I understand correctly, the code you shared in your second point could look like this, in context:

``` 
def get_deal_ids(self, tap):
    # Store the start_time before entering the loop
    stream_start = pendulum.now()
        while self.more_items_in_collection:
            ...
            this_page_ids = [response.json()['data'][i]['id'] for i in range(ndeals) 
             if response.json()['data'][i]['stage_change_time'] is not None 
             and pendulum.parse(response.json()['data'][i]['stage_change_time']) >= {some_time_variable}
             and pendulum.parse(response.json()['data'][i]['stage_change_time']) <= stream_start]
            ...
```

Does that make sense?

**Comment by Forestk11** [comment] 2018-10-16 17:16
Hey there I'm looking into this because I also have the same problem. 

I would ideally want to get stitch to not sync the "dealflow" table - because I essentially don't need it. Do you know of a way to do that?

Thanks in advance

**Comment by dmosorast** [comment] 2018-10-16 22:00
@Forestk11 The fix to add bookmarking to the `dealflow` table has been merged and released. In practice, this should greatly reduce the rows synced by that table. If you run into problems with it, feel free to open another issue on this repo.

As for your question, the Singer platform supports allowing the tap to describe what streams/tables should be synced. This is called the [discovery mode](https://github.com/singer-io/getting-started/blob/master/docs/DISCOVERY_MODE.md). In order to provide table selection, the tap would need to implement the `--discovery` command line argument, and publish a catalog that describes the available tables and fields. It would then need a modification to consume that catalog during sync mode and only request and emit data for the tables marked as `selected` in the catalog.

Closing this issue since a fix has been released, and field selection would be an unrelated feature addition.

**Closed by dmosorast** 2018-10-16 22:00 UTC
Labels: help wanted

**Comment by Forestk11** [comment] 2018-10-18 14:02
Ah yes it now appears to have solved the issue. Thank you for your help!

Forest
